POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "roma@mail.ru",
  "password": "123456"
}


##########
GET http://localhost:3000/users/6279bb57010dfe85177b4b82


######

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Rг",
  "about": "Simply the best",
  "avatar": "https://mirplaneta.ru/images/5/920.jpg"
}

########

DELETE  http://localhost:3000/cards/6287ba60c28e291b132acf80
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg1YWQ2NWQzZTgzMTAxNjQxNGE3N2MiLCJpYXQiOjE2NTMwMDg0MDksImV4cCI6MTY1MzYxMzIwOX0.sjUMJDs1h3HrdAtBZvKsXq1S5Tlk3MxEzzvQoAn9NgI



#####
POST  http://localhost:3000/cards
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg1YWQ2NWQzZTgzMTAxNjQxNGE3N2MiLCJpYXQiOjE2NTMwMDg0MDksImV4cCI6MTY1MzYxMzIwOX0.sjUMJDs1h3HrdAtBZvKsXq1S5Tlk3MxEzzvQoAn9NgI

{
  "name": "gp",
  "link": "gsdfgsdfgsdfgsdfgdsgf"
}

#####



PUT http://localhost:3000/cards/627d503e75dab275fc9782b4/likes
Content-Type: application/json

#####

get http://localhost:3000/users/me
Content-Type: application/json

